config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'slayerz#home', as: 'home'
  resources :slayerz, :jobs
  post '/slayerz/become_slayer', to: 'slayerz#turn_into_slayer', as: 'new_slayer'
  patch '/jobs/:id/accepted_job', to: 'jobs#accepted_job', as: 'accepted'

  resources :conversations do
    resources :messages
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :description, presence: true
  validates :amount, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: 1 }
end

app/models/roles.rb
class Roles < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/slayer_info.rb
class SlayerInfo < ApplicationRecord
  belongs_to :user
  # belongs_to :race
  has_many :jobs

  has_one_attached :profile_image
end

app/models/user.rb
class User < ApplicationRecord
  rolify :role_cname => 'Roles'
  has_many :jobs, dependent: :destroy
  has_one :role
  has_one :slayer_info, dependent: :destroy
  validates :username, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  acts_as_messageable

  def name
    "User #{id}"
  end

  def mailboxer_email(object)
    nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Ensure user is logged in before accessing certain views
    before_action :authenticate_user!, except: [:index, :show]
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    include Pundit

    # If user is not authorised, rescue with the following 
    rescue_from Pundit::NotAuthorizedError, with: :forbidden

    # Display forbidden error message
    private
    def forbidden
        flash[:alert] = "Slayerz are not authroised to perform that action."
        redirect_to request.referrer || home_path
    end

    # sanitize login 
    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

    def index
        @conversations = current_user.mailbox.conversations
    end

    def show
        @conversation = current_user.mailbox.conversations.find(params[:id])
    end

    def new
        @recipients = User.all - [current_user]
    end

    def create
        @recipient = User.find(params[:user_id])
        receipt = current_user.send_message(@recipient, params[:body], params[:subject])
        redirect_to conversation_path(receipt.conversation)
    end

    
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
    before_action :check_auth, except: [:index]
    
    # Display all unaccepted jobs
    def index
        @jobs = Job.all
    end
    
    # Get job by ID and display individual job view to the user
    def show
        @job = Job.find(params[:id])
        @current_job = Job.find(params[:id])
    end

    def new
    end
    
    #Create new job and save job, redirect to jobs page
    def create
        @job = Job.new(job_params)
        
        @job.user_id = current_user.id
        if (@job.save)
            redirect_to @job
        else 
            flash.now[:errors] = @job.errors.full_messages
            render action: 'new'
        end
    end

    # Get job ID with params and edit job
    def edit
        @job = Job.find(params[:id])
    end

    # Method to update job
    def update
        @job = Job.find(params[:id])
        
        if @job.user_id = current_user.id
            (@job.update(job_params))
            redirect_to @job
        else 
            render 'edit'
        end
    end

    # Enable slayers to accept a job
    def accepted_job
        @current_job = Job.find(params[:id])
        
        if @current_job.accepted == nil
            @current_job.update(accepted: current_user.first_name)
            redirect_to jobs_path
        end
    end

    # Destroy job
    def destroy
        @job = Job.find(params[:id])
        @job.destroy

        redirect_to jobs_path
    end

    # Authorise creation of job
    def check_auth
        authorize Job
    end

    # sanatise 
    private
    def job_params
        params.require(:job).permit(:title, :description, :amount, :accepted)
    end

    # Sanitise accepted job status
    def accepted_job_params
        params.require(:job).permit(:accepted)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :set_conversation

    def create
        receipt = current_user.reply_to_conversation(@conversation, params[:body])
        redirect_to conversation_path(receipt.conversation)
    end

    private
    def set_conversation
        @conversation = current_user.mailbox.conversations.find(params[:conversation_id])

    end
end

app/controllers/slayers_controller.rb
class SlayersController < ApplicationController
    def index
    end

    def show
    end
end

app/controllers/slayerz_controller.rb
class SlayerzController < ApplicationController
    before_action :authenticate_user!, only: [:create, :edit, :destroy]
    
    # Application home page
    def home
        @users = User.all
        slayer_role = Roles.find_by(name: 'slayer')
        @slayers = Roles.find_by_name('slayer').users
        
        @slayers = @slayers.sample(3)

        
        @jobs = Job.all
        @jobs = @jobs.sample(5)
        
    end

    # Slayers index page, displaying all slayers for users to browse and message directly.
    def index
        slayer_role = Roles.find_by(name: 'slayer')
        @users = slayer_role.users
    end

    # Show individual slayer page  
    def show
        @slayer = SlayerInfo.find(params[:id])
    end

    # Create slayer profile
    def create
        @slayer_info = SlayerInfo.find_by(user_id: current_user.id)
        if @slayer_info
            if @slayer_info.update(profile_params)
                redirect_to slayerz_path(@slayer_info)
            else
                render 'new'
            end
        else
            @slayer_info = SlayerInfo.new(profile_params)
            @slayer_info.user_id = current_user.id
            if (@slayer_info.save!)
                redirect_to slayerz_path(@slayer_info)
            else
                render 'new'
            end
        end
    end

    # Edit slayer
    def edit
        @slayer_info = SlayerInfo.find(params[:id])
    end

    # Update slayer information
    def update
        @slayer_info = SlayerInfo.find(params[:id])
        
        if @slayer_info.user_id = current_user.id
            (@slayer_info.update(profile_params))
            redirect_to slayerz_path(@slayer_info)
        else 
            render 'edit'
        end
    end

    # Enable user to turn into slayer
    def turn_into_slayer
        current_user.add_role :slayer
        if current_user.slayer_info == nil
            SlayerInfo.create(user_id: current_user.id )
        end
        redirect_to new_slayerz_path
    end

    # sanitise upddation of slayer information
    private
    def profile_params
        params.require(:slayer_info).permit(:weapon, :biography, :profile_image)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/slayerz_helper.rb
module SlayerzHelper
end

app/views/conversations/index.html.erb
<h3>Messages</h3>

<div class="show-container">
    <div class="show-info">
        <h5>Current conversations</h5>
        <% @conversations.each do |conversation| %>
            <%= link_to conversation.subject, conversation_path(conversation) %>
        <% end %>
        <br><br><br>
        <%= link_to "New Message", new_conversation_path%>
     </div>
</div>

app/views/conversations/new.html.erb
<h2>New Message</h2>

<%= form_tag conversations_path, method: :post do %>

<div>
    <%= select_tag :user_id, options_from_collection_for_select(@recipients, :id, :first_name)%> 

</div>
    <%= text_field_tag :subject, nil, placeholder: "Subject" %> 
<div>
</div>

<div>
    <%= text_area_tag :body, nil, placeholder: "Leave a message.. " %> 
</div>

    <%= submit_tag %>
<% end %>

app/views/conversations/show.html.erb
<h2><%= @conversation.subject %></h2>

<% @conversation.receipts_for(current_user).each do |receipt| %>
<div>
    <% receipt.message.sender.first_name%> messaged:
    <p><%= receipt.message.body%></p>
</div>

<% end %>

<%= form_tag conversation_messages_path(@conversation), method: :post do %>
<div>
    <%= text_area_tag :body%>
</div>

    <%= submit_tag %>


<% end %>

app/views/jobs/edit.html.erb
<h1>edit hunt</h1>

<%= form_for :job, url: job_path(@job), method: :patch do |f|%>

    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :description %>
    <%= f.text_area :description %>

    <%= f.label :amount %>
    <%= f.number_field :amount%>
    
    <%= f.submit %>
<% end %>

app/views/jobs/index.html.erb
<div class="content">
<h5>Choose a hunt from those available below. </h5>
</div>
   <div class="job-container">
        <% @jobs.each do |job| %>
            <div class="job-card">
            <h4><%= job.title%></h4>
            <p><%= job.description%></p>
            <p><%= job.amount%></p>
            <%= link_to 'View more', job_path(job)%>
            </div>
        <% end %> 
    </div>

app/views/jobs/new.html.erb
<h1>Create a job</h1>

<%= form_for :job, url: jobs_path do |f|%>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :description %>
    <%= f.text_area :description %>

    <%= f.label :amount %>
    <%= f.number_field :amount%>
    

    

    <%= f.submit %>
<% end %>

app/views/jobs/show.html.erb
<!-- View for individual job pages -->

<div class="show-container">
    <div class="show-info">
        <h3><%= @job.title %></h3>
        <hr>
        <p>
            <%= @job.description%>
            <%= @job.amount%>

            
        </p>

        <p><strong> Hunt created by: </strong><%= @job.user.first_name %></p>

        <% if @job.accepted %>
            <p> Sorry! This hunt is no longer available. It was accepted by <%= @job.accepted %></p>
            <% else %>
            <p>This Hunt is still available! Accept it now.</p>
        <%end %>



        <% if current_user.has_role?(:slayer) && @job.accepted == nil %>
            <%= link_to "Accept Hunt", accepted_path, method: :patch %>
        <% elsif !current_user.has_role?(:slayer) %>
            <%= link_to "Edit", edit_job_path(@job) %>
            <%= link_to "Delete", job_path(@job),  
                method: :delete,
                data: {confirm: "Are you sure you want to remove the hunt?"} %>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Slayerz - Find and hire demons to help you with a problem.</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <!-- Main navigation -->
  <header>
  <h1>Slayerz</h1>
  <% if user_signed_in? %>
  <nav>
    <div class="nav-area">
        <%= link_to "Home", home_path %>
          <% if !current_user.has_role? :slayer%>
            <%= link_to "Create Hunt", new_job_path %>
          <% end %>
        <%= link_to "View Hunts", jobs_path %>
        <%= link_to "Slayerz", slayerz_index_path %>
        <%= link_to "Account", edit_user_registration_path %>
        <%= link_to "Messages", conversations_path%>
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    </div>
  </nav>
  <% end%>
        
  </header>

  <body>
  <% if notice %>
    <p class="notice"><%= notice %></p>
  <% end %>

  <% if alert %>
    <p class="alert"><%= alert %></p>
  <% end %>

  <% if flash[:errors] %>
    <section class="errors">
      <p class="title">The following errors occured:</p>
      <ul>
      <% flash[:errors].each do |error| %>
        <li><%= error %></li>
      <% end %>
      </ul>
    </section>
  <% end %>

  <main>
    <%= yield %>
  </main>
  </body>
</html>

app/views/slayerz/create.html.erb
<%= form_with @user do |f| %>
    <%= f.text_field :weapon%>
    <%= f.text_area :bio%>
    <%= f.collection_select :bio%>
<% end %>

app/views/slayerz/edit.html.erb
<h3>Edit your Slayer profile here</h3>

<div class="field"> 
<%= form_for :slayer_info, url: slayerz_path(@slayer_info), method: :patch do |f| %>
    
    <%= f.label :weapon %><br />
    <%= f.text_field :weapon, class: "form-control"%>
<br /><br />
    <%= f.label :biography %><br />
    <%= f.text_area :biography, class: "form-control profile"%>

<br /><br />
    <%= f.label :profile_image %><br />
    <%= f.file_field :profile_image, class: "form-control profile" %>

    <%# <%= f.label :race %>
    <%# <%= f.collection_select :race, @races, :id, :race_name %>
<br /><br />
    <%= f.submit "Update profile"%>
<% end %>
</div>

app/views/slayerz/home.html.erb
<section class="hero">

  <h2>Welcome to Slayerz!</h2>
    <h6>Slayerz is an online marketplace for weaklings and demons to connect and help each other. </h6>

    <% if user_signed_in? %>
        
    <% else %>
        <div class="btn-container">
            <%= link_to "Login", new_user_session_path, class: "btn-empty" %>
            <%= link_to "Register", new_user_registration_path, class: "btn-full"%>
        </div>
    <% end %>
</section>

<% if user_signed_in? %>
    <section class="slayers">
        <h3>Featured Slayerz</h3>
        <div class="slayerz-container">

        
            <% @users.each do |user| %>
                <div class="slayerz-card">
                    <% if user.has_role?(:slayer) && user.slayer_info %>
                        <% if user.slayer_info.profile_image.attached?%>
                        <p><%= cl_image_tag user.slayer_info.profile_image.key, crop: :scale, class: "style-img", cloud_name: 'kate-anisha' %></p>
                    <% end %>
                    <%= user.first_name%> <%= user.last_name%>
                    <%= link_to 'Hire me', slayerz_path(user.slayer_info) %>
                </div>
                <% end %>
            <% end %>
        </div>
    </section>


    <section class="jobs">
    <h3>Available Hunts</h3>
        <div class="job-container">
            <% @jobs.each do |job| %>
                <div class="job-card">
                    <h4><%= job.title%></h4>
                    <p><%= job.description%></p>
                    <%= link_to 'View Hunt', job_path(job)%>
                </div>
            <% end %> 
        </div>
    </section>

<% end %>

app/views/slayerz/index.html.erb
<h3>All Slayerz</h3>

<div class="slayerz-container">
    <% @users.each do |user| %>
        <div class="slayerz-card">
            <% if user.has_role?(:slayer) && user.slayer_info %>
                <% if user.slayer_info.profile_image.attached?%>
                <p><%= cl_image_tag user.slayer_info.profile_image.key, crop: :scale, class: "style-img", cloud_name: 'kate-anisha' %></p>
            <% end %>
            <%= user.first_name%> <%= user.last_name%>
            <%= link_to 'Hire me', slayerz_path(user.slayer_info) %>
        </div>
        <% end %>
    <% end %>
</div>

app/views/slayerz/new.html.erb
<H1>Slayer profile</H1>

<%= form_for :slayer_info, url: slayerz_index_path do |f| %>
    <%= f.label :weapon %>
    <%= f.text_field :weapon%>

    <%= f.label :biography %>
    <%= f.text_area :biography%>

    <%= f.label :profile_image %>
    <%= f.file_field :profile_image %>
    
    <%= f.submit %>
<% end %>

app/views/slayerz/show.html.erb
<!-- View for individual slayer profiles -->

<div class="show-container">
    <div class="show-info">
        <% if @slayer.profile_image.attached?%>
            <p><%= cl_image_tag @slayer.profile_image.key, crop: :scale, width: 500, cloud_name: 'kate-anisha' %></p>
        <% end %>
        <h3><%= @slayer.user.first_name %> <%= @slayer.user.last_name %></h3>
        <hr>
        <p><strong>Name:</strong> <%= @slayer.user.first_name %> <%= @slayer.user.last_name %> </p>
        <p><strong>Weapon:</strong>  <%= @slayer.weapon %></p>
        <p><strong>Biography:</strong>  <%= @slayer.biography %></p>
        <%= link_to "Contact", conversations_path, class: "btn-empty" %>
    </div>
</div>